/**
 * Created by Rajinda on 4/27/2016.
 */

angular.module('authServiceModule' ,[])
.service('authService', function () {
    this.Token = "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ3YXJ1bmFAZHVvc29mdHdhcmUuY29tIiwianRpIjoiYjJlOWRkZTQtNzFlMi00NDBmLThiYmQtOTc1ODBjZDc1MjUyIiwic3ViIjoiYjgzZjM2MWQtNWY4NS00ZDIzLTg2NzctMGMyNGYxYjk0ZTU0IiwiZXhwIjoxNDY1NTUwMjc0LCJ0ZW5hbnQiOiIxIiwiY29tcGFueSI6IjEiLCJjbGllbnQiOiIxIiwic2NvcGUiOlt7InJlc291cmNlIjoiYXR0cmlidXRlIiwiYWN0aW9ucyI6WyJyZWFkIiwid3JpdGUiLCJkZWxldGUiXX0seyJyZXNvdXJjZSI6ImFsbCIsImFjdGlvbnMiOlsicmVhZCIsIndyaXRlIiwiZGVsZXRlIl19XSwiaWF0IjoxNDY0OTQ1NDc0fQ.s4f5X1PiYSccANGIzulcseR_EcigI_3pOvXccLktvZs";// response.data;
    this.TokenWithoutBearer = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzdWtpdGhhIiwianRpIjoiMTdmZTE4M2QtM2QyNC00NjQwLTg1NTgtNWFkNGQ5YzVlMzE1Iiwic3ViIjoiNTZhOWU3NTlmYjA3MTkwN2EwMDAwMDAxMjVkOWU4MGI1YzdjNGY5ODQ2NmY5MjExNzk2ZWJmNDMiLCJjbGllbnQiOiIxIiwiZXhwIjoxODkzMzAyNzUzLCJ0ZW5hbnQiOjEsImNvbXBhbnkiOjMsInNjb3BlIjpbeyJyZXNvdXJjZSI6ImFsbCIsImFjdGlvbnMiOiJhbGwifV0sImlhdCI6MTQ2MTI5OTE1M30._M8u4ElZESTdJtkQSEtr58kE97s0KiHeIaeWsoVc8Ho";// response.data;
});
